### ISSUE TITLE
Left-Frob Melee Weapon not being applied to certain windows

### ISSUE THREAD

**Issue by tunbridgep** [tunbridgep/gmdx-vrsd-fork#40]
The windows in the command area in Brooklyn Naval Shipyards don't select melee weapons when left-frobbed.

**Comment by ISuckM8** [comment]
This is a general problem with windows, if you try to left frob the window in the Osgoods store  (is that the name? The store in NYC right next to the initial shootout) it won't do anything. My guess is that this is either because the windows aren't assigned a proper class, or most likely this wasn't added to their class.

**Comment by ISuckM8** [comment]
I'll take this up if it's a code problem

**Comment by tunbridgep** [comment]
Fixed.
